In this notebook, I present the very basics to get started with numpy operations.

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([a,b])
d = np.array([b,a])

Basic operations are pretty intuitive

In [4]:
a + b

array([5, 7, 9])

In [5]:
a - b

array([-3, -3, -3])

In [6]:
a * b

array([ 4, 10, 18])

In [8]:
a @ b  # Dot product

32

Usin np.max we can determine the max value in any given axis

In [7]:
two_array = np.array([[1,2,3,4,15],[6,7,8,9,0]])
print(np.max(two_array, axis=1))
print(np.max(two_array, axis=0))

[15  9]
[ 6  7  8  9 15]
