In this notebook, I present the very basics to get started with numpy operations.

In [12]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([a,b])
d = np.array([b,a])

Basic operations are pretty intuitive

In [4]:
a + b

array([5, 7, 9])

In [5]:
a - b

array([-3, -3, -3])

In [6]:
a * b

array([ 4, 10, 18])

In [8]:
a @ b  # Dot product

32